#!/bin/bash
set -eux -o pipefail

stack --stack-yaml stack-ghcjs.yaml build anapo:test-app
dist_dir=$(stack --stack-yaml stack-ghcjs.yaml path --dist-dir)
bin_dir="$dist_dir/build/test-app/test-app.jsexe"
./serve-test-app.hs "$bin_dir" "test-app.html"
